version: '3.8'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    image: mmahmadi0101/ideablog
    working_dir: /usr/src/ideablog
    ports:
      - 8005:8005
    networks:
      - ideablog_network
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pguser_django
      - POSTGRES_PASSWORD=pgpassword_django
      - POSTGRES_DB=pgdb_dajngo
    networks:
      - ideablog_network

volumes:
  postgres_data:

networks:
  ideablog_network:
    driver: bridge
