version: '3.8'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    image: mmahmadi0101/ideablog
    working_dir: /usr/src/ideablog
    entrypoint: /usr/src/ideablog/entrypoint.sh
    ports:
      - 8005:8005
    networks:
      - net
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  net:
    driver: bridge
