version: '3.8'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/ideablog
    entrypoint: /usr/src/ideablog/entrypoint.sh
    ports:
      - 8005:8005
    networks:
      - net
    volumes:
      - db_data:/usr/scr/ideablog/db.sqlite3
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  net:
    driver: bridge

volumes:
  db_data:
