# Generated by Django 3.1.3 on 2020-12-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
