# Generated by Django 3.1.3 on 2021-02-05 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_idea_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='like',
        ),
        migrations.AddField(
            model_name='idea',
            name='unlikes',
            field=models.ManyToManyField(related_name='blogpost_unlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
