# Generated by Django 3.1.3 on 2021-02-05 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20210205_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='unlikes',
        ),
        migrations.AddField(
            model_name='idea',
            name='dislikes',
            field=models.ManyToManyField(related_name='blogpost_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
